
name: cdkbump
on:
  push:
    branches:
      bump/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "false"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/bump/})"
        id: extract_branch
      - name: Synthesize project files
        run: CDK_VERSION=${{ steps.extract_branch.outputs.branch }} npx projen
      - name: Set git identity
        run: |-
          git config user.name "Auto-bump"
          git config user.email "github-actions@github.com"
      - name: Commit and push changes (if any)
        run: 'git diff --exit-code || ((git add package.json yarn.lock .projen/deps.json) && (git commit -m "chore: bumping CDK version" && git push origin))'
    container:
      image: jsii/superchain
